version: '3'

services:
  ordering-service:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/code
    env_file:
      - .env
    ports:
      - '8090:8090'
    environment:
      ELASTICSEARCH_ENDPOINT: 'http://elasticsearch:9200'
    restart: always
    depends_on:
      - elasticsearch
      - kibana

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.2
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"

  kibana:
    container_name:   kibana
    image: docker.elastic.co/kibana/kibana:7.14.2
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
