version: '3.1'

services:
  ordering-service:
    container_name: ordering-service
    build:
      context: .
    volumes:
      - .:/home/userapp/app/.
    env_file:
      - .env
    ports:
      - '8000:8000'
    environment:
      MONGO_SERVER: order-aggregate-repository_mongo-db
      MONGO_PORT: '27017'
      MONGO_USERNAME: root
      MONGO_PASSWORD: admin
      ENVIRONMENT: development
    restart: always
    depends_on:
      - order-aggregate-repository_mongo-db
      - ordering-event-bus

  order-aggregate-repository_mongo-db:
    image: mongo:5.0
    container_name: order-aggregate-repository_mongo-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - '27018:27017'
    restart: always

  ordering-event-store-repository_mongo-db:
    image: mongo:5.0
    container_name: ordering-event-store-repository_mongo-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - '27019:27017'
    restart: always

  ordering-redis:
    image: "redis:alpine"
    container_name: ordering-redis
    command: redis-server
    ports:
      - "6379:6379"

  ordering-event-store-repository_admin-mongo:
    image: 0x59/admin-mongo:latest
    container_name: ordering-event-store-repository_admin-mongo
    environment:
      PORT: 1234
      CONN_NAME: ordering-event-store-repository_mongo-db
      DB_HOST: 27017
    restart: unless-stopped
    ports:
      - "1234:1234"
    links:
      - ordering-event-store-repository_mongo-db
    depends_on:
      - ordering-event-store-repository_mongo-db

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  ordering-event-bus-kafka:
    image: confluentinc/cp-kafka:latest
    container_name: ordering-event-bus-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://ordering-event-bus-kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
