version: '3'

services:
  ordering-service:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/code
    env_file:
      - .env
    ports:
      - '8090:8090'
    environment:
      MONGO_SERVER: event-source-mongo-db
      MONGO_PORT: '27017'
      MONGO_USERNAME: root
      MONGO_PASSWORD: admin
    restart: always
    depends_on:
      - mongo-db
      - kafka

  order-aggregate-repository_mongo-db:
    image: mongo:5.0
    container_name: order-aggregate-repository_mongo-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - '27018:27017'
    restart: always

  order-event-store-repository_mongo-db:
    image: mongo:5.0
    container_name: order-event-store-repository_mongo-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - '27017:27017'
    restart: always

  redis:
    image: "redis:alpine"
    container_name: mk-crud-application-redis
    command: redis-server
    ports:
      - "6379:6379"

  order-aggregate-repository_mongo-db-express:
    image: mongo-express
    container_name: order-aggregate-repository_mongo-db-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_OPTIONS_EDITORTHEME: dracula
      ME_CONFIG_MONGODB_URL: mongodb://admin:root@order-aggregate-repository_mongo-db:27017/
    depends_on:
      - mongo-db

  order-event-store-repository_mongo-db-express:
    image: mongo-express
    container_name: order-event-store-repository_mongo-db-express
    restart: unless-stopped
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_OPTIONS_EDITORTHEME: dracula
      ME_CONFIG_MONGODB_URL: mongodb://admin:root@order-event-store-repository_mongo-db:27017/
    depends_on:
      - mongo-db

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper